sonar.projectName=PHPStan Rules
sonar.projectKey=phpstan-rules

sonar.sources=src
sonar.tests=tests
sonar.exclusions=

sonar.sourceEncoding=UTF-8
sonar.language=php

sonar.phpUnit.coverage.analyzeOnly=true
sonar.php.coverage.reportPaths=coverage.xml
