name: phpstan-rules

x-base: &base
  tty: true
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    PHP_IDE_CONFIG: serverName=iwf-phpstan-rules # for PHPStorm debugging
  command: >
    sh -c "composer update &&
           composer test"
  volumes:
    - ./../..:/app
    - ~/.ssh:/root/.ssh

services:
  php85:
    <<: *base
    container_name: iwf-phpstan-rules-php85
    build:
      context: ../build
      args:
        PHP_VERSION: "8.5"
        XDEBUG: "${XDEBUG:-true}"
  php84:
    <<: *base
    container_name: iwf-phpstan-rules-php84
    build:
      context: ../build
      args:
        PHP_VERSION: "8.4"
        XDEBUG: "${XDEBUG:-true}"
  php83:
    <<: *base
    container_name: iwf-phpstan-rules-php83
    build:
      context: ../build
      args:
        PHP_VERSION: "8.3"
        XDEBUG: "${XDEBUG:-true}"
